version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-occurrence
    environment:
      POSTGRES_DB: occurrence-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge